version: '3'

services:
  nginx:
    image: nginx:stable
    depends_on:
      - php
      - mysql
    container_name: nginx
    ports:
      - "8083:80"
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
  mysql:
    image: mysql:8.0.29-oracle
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: laravel
      # MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: congnt
        uid: 1000
    container_name: php
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    ports:
      - "8081:80"
    networks:
      - laravel
networks:
  laravel:
